language: python
python:
- "3.7"
- "3.6"
- "2.7"
os:
- linux
- osx
before_install:
- pip install pytest pytest-cov coveralls
install:
- pip install -e .
script:
- pytest --cov --cov-report=xml:$(pwd)/coverage.xml
after_success:
- coveralls
